name: Feature request
description: Request a new feature.
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees:
  - gjong
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request! Please provide as much
        information as possible to help us understand your request.
  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: Provide a brief explanation of the feature
      placeholder: Describe in a few lines your feature request
    validations:
      required: true
  - type: textarea
    id: alternatives-feature
    attributes:
      label: What alternatives have you considered?
      description: Please describe if you have already thought of alternatives.
      placeholder: Tell us what things do not completely cover your needs, but that you did consider!
  - type: textarea
    id: unresolved_question
    attributes:
      label: "Open questions"
      description: What questions still remain unresolved ?
      placeholder: Identify any unresolved issues.
    validations:
      required: false
